const String supabaseUrl = "https://knhziqhnlxwfmzznurjn.supabase.co";
const String supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuaHppcWhubHh3Zm16em51cmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNTc2NzMsImV4cCI6MjA0OTkzMzY3M30.VjWcxvmhwfmyKX3kPUvYZyGX6rPJ493XsAMq4W27lEk";
